# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(workspace: "ColorLight.xcworkspace", scheme: "ColorLight")
    upload_to_testflight
  end

  desc "Runs all the tests"
  lane :test do
    xctest(
      clean: false,
      code_coverage: true,
      scheme: "ColorLight",
      workspace: "ColorLight.xcworkspace",
      destination: "platform=iOS Simulator,name=iPhone SE (2nd generation)",
      skip_detect_devices: true
    )
  end
end
